CREATE DATABASE IF NOT EXISTS DB_PHP;
use DB_PHP;
DROP TABLE IF EXISTS AUTHENTICATION_ATTEMPTS;

CREATE TABLE AUTHENTICATION_ATTEMPTS (
	  AttemptID		    BIGINT		    NOT NULL auto_increment
	, AttemptedUsername	VARCHAR(200)	NOT NULL
	, WasSuccessful		TINYINT(1)		NOT NULL
	, SuccessfulUserID	TINYINT(1)		NOT NULL
	, AttemptedOn		TIMESTAMP		NOT NULL
	, AttemptedIP		VARCHAR(50)		NOT NULL

	, PRIMARY KEY (AttemptID)
);
