CREATE DATABASE IF NOT EXISTS DB_PHP;
use DB_PHP;
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE USER_ROLES (
	  User_RoleID		INT		NOT NULL auto_increment
	, UserID		    INT		NOT NULL
	, RoleID		    INT		NOT NULL

	, PRIMARY KEY (User_RoleID)
	, UNIQUE KEY User_Roles_IDX0 (UserID, RoleID)
);


INSERT INTO USER_ROLES
(
      UserID
    , RoleID
)
VALUES
(
      1
    , 1
);