CREATE DATABASE IF NOT EXISTS DB_PHP;
use DB_PHP;
DROP TABLE IF EXISTS QUIZ_QUESTION_OPTIONS;

CREATE TABLE QUIZ_QUESTION_OPTIONS (
	  QuestionOptionID	INT		        NOT NULL auto_increment
	, QuestionID	    INT				NOT NULL
	, Text				VARCHAR(2000)	NOT NULL
	, IsAnswer			BIT				NOT NULL
	, PRIMARY KEY (QuestionOptionID)
);
